FROM ruby:3.4.2

# Rails app lives here
WORKDIR /app

# Install Linux dependencies
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# Install gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the rest of the code
COPY . .

COPY ./bin/docker-entrypoint /usr/bin/docker-entrypoint
RUN chmod +x /usr/bin/docker-entrypoint

ENTRYPOINT ["/usr/bin/docker-entrypoint"]

# Expose the port Rails runs on
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
